name: Docker Image CI

on:
  push:
    tags:
      - v**

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Get Docker Image Url
      id: image
      env:
        URL: harbor.ncuos.com/genius-auth/core
      run: |
        echo LATEST=${URL}:latest >> $GITHUB_OUTPUT
        echo VERSION=${URL}:${GITHUB_REF/refs\/tags\//} >> $GITHUB_OUTPUT
    
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile \
        --tag ${{ steps.image.outputs.VERSION }}
        --tag ${{ steps.image.outputs.LATEST }}

    - name: Push the Docker image
      run: |
        docker push ${{ steps.image.outputs.VERSION }}
        docker push ${{ steps.image.outputs.LATEST }}
